Finish pull request
GeorgiyPol/Pomodoro-App pull request #1
Opened 2022-05-22 11:44 UTC by georg1856

2022-05-23 18:01 UTC, KazankovDmitriy reviewed
Привет, Георгий! Проверил работу таймера и код. По коду всё достаточно неплохо: он аккуратный, в целом хорошо читаемый, реализация интересная, но есть замечания, которые можешь посмотреть в комментариях к строкам файлов в ПР.
По работе самого таймера и внешнему виду есть тоже замечания:
- кнопка стоп на малых разрешениях экрана (например модели mini) накладывается на label, а на большом разрешении (модели pro max) находится высоко и далеко от кнопок - думаю стоит пересмотреть констрэйнты
- когда ставишь на паузу и потом, например спустя секунду, нажимаешь на play, время некорректно соотносится с анимацией круга. Это заметно когда время в секундах. В минутах это не будет так заметно, но будет хорошо, если этот нюанс всё равно будет учтён
- для запуска проекта пришлось указать корректный адрес для аудиофайла, это не столь критично, так как этого не было в задании

В целом работа неплохая, но есть недочеты, которые нужно всё таки поправить, буду ждать правок, если будут вопросы по трактовке замечаний пиши мне, реализацию можно обсудить в командном чате.

2022-05-23 18:01 UTC, KazankovDmitriy commented on PomodoroApp/PomodoroApp/Animation.swift
> +        }
Такую вложенность условных конструкций if можно упростить, например передавая в методы проверяемое значение, а также использованием тернарного оператора. Этим самым можно и методы сделать более универсальными, и уменьшить количество строк кода

2022-05-23 18:01 UTC, KazankovDmitriy commented on PomodoroApp/PomodoroApp/AppDelegate.swift
> +    }
Неиспользуемые методы в будущем лучше удалять

2022-05-23 18:01 UTC, KazankovDmitriy commented on PomodoroApp/PomodoroApp/Extension.swift
> +            startButton.bottomAnchor.constraint(equalTo: view.bottomAnchor, constant: -350),
Числовые значения здесь и далее можно выносить в Метрики

2022-05-23 18:01 UTC, KazankovDmitriy commented on PomodoroApp/PomodoroApp/SceneDelegate.swift
> +    }
Аналогично можно удалить неиспользуемые методы

2022-05-23 18:01 UTC, KazankovDmitriy commented on PomodoroApp/PomodoroApp/ViewController.swift
> +        if isWorkTime {
Аналогично вложенность условных конструкций можно упростить.

2022-05-23 18:03 UTC, KazankovDmitriy requested changes
Привет, Георгий! Проверил работу таймера и код. По коду всё достаточно неплохо: он аккуратный, в целом хорошо читаемый, реализация интересная, но есть замечания, которые можешь посмотреть в комментариях к строкам файлов в ПР.
По работе самого таймера и внешнему виду есть тоже замечания:
- кнопка стоп на малых разрешениях экрана (например модели mini) накладывается на label, а на большом разрешении (модели pro max) находится высоко и далеко от кнопок - думаю стоит пересмотреть констрэйнты
- когда ставишь на паузу и потом, например спустя секунду, нажимаешь на play, время некорректно соотносится с анимацией круга. Это заметно когда время в секундах. В минутах это не будет так заметно, но будет хорошо, если этот нюанс всё равно будет учтён
- для запуска проекта пришлось указать корректный адрес для аудиофайла, это не столь критично, так как этого не было в задании

В целом работа неплохая, но есть недочеты, которые нужно всё таки поправить, буду ждать правок, если будут вопросы по трактовке замечаний пиши мне, реализацию можно обсудить в командном чате.

2022-05-25 06:23 UTC, georg1856 commented
Недостатки исправлены.

2022-05-25 06:24 UTC, closed without merging